#!/usr/bin/env bash

set -x -e

# Close System Settings to prevent interference
osascript -e 'tell application "System Settings" to quit'

##############
#  Keyboard  #
##############

# Input Sources > Select next source in input menu
defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 61 "<dict><key>enabled</key><false/></dict>"

# Input Sources > Select the previous input source
#  ~> Cmd + Space
defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 60 \
  "<dict><key>enabled</key><true/><key>value</key><dict><key>type</key><string>standard</string>
    <key>parameters</key><array><integer>32</integer><integer>49</integer><integer>1048576</integer></array></dict></dict>"

# Spotlight > Show Spotlight search
#  ~> Ctrl + Space
defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 64 \
  "<dict><key>enabled</key><true/><key>value</key><dict><key>type</key><string>standard</string>
    <key>parameters</key><array><integer>32</integer><integer>49</integer><integer>262144</integer></array></dict></dict>"

#################
#  Screenshots  #
#################

# Screenshot location
mkdir -p ~/Desktop/screenshots
defaults write com.apple.screencapture location -string ~/Desktop/screenshots

# Restart defaults server to apply settings
killall cfprefsd

###################
#  Google Chrome  #
###################

# NOTE: com.apple.universalaccess is TCC-protected. If the Chrome shortcuts do
# not show up, grant Full Disk Access to the terminal running this script, or
# tick Chrome under System Settings > Keyboard > Keyboard Shortcuts > App Shortcuts.
sudo defaults write com.apple.universalaccess com.apple.custommenu.apps -array com.google.Chrome
defaults write com.google.Chrome NSUserKeyEquivalents -dict 'Select Next Tab' '@$]' 'Select Previous Tab' '@$['
